#import "template.typ": *

= Planning in Robotics and AI

#informally(title: "What is Planning?")[
  Remember that there is not a single, universally accepted definition of *planning*. Substantially, it can be viewed as one of the primary contact points between the fields of Robotics and Artificial Intelligence (AI). It is the process of computing a sequence of actions to achieve a specific goal.
]

== Deterministic Planning

In a deterministic planning scenario, the problem is defined by three main components:
- An *Initial State*
- A *Goal State* (or a set of goal states)
- A *Transition Model*

In *deterministic planning*, the transition model is completely deterministic. This means that if the robot applies a specific action in a specific state, the next state is known with absolute certainty. There is no noise or uncertainty in the transition.

Thanks to this assumption, we can represent the transition model simply as a mathematical function: $T: S times A -> S$. There is no randomness involved.

#note(title: "Why use deterministic models?")[
  Sometimes it is highly convenient to assume that the world is deterministic. This assumption massively simplifies the planning process and works surprisingly well in many real-world robotic problems. 
]

*How do we solve a deterministic problem formulated in these terms?*
Usually, the solution relies on a *Search Algorithm*. These algorithms historically come from the AI domain rather than pure robotics, and they explore the state space to find a valid sequence of actions reaching the goal.

== Feedback Planning (Stochastic Planning)

Basically, in this paradigm, we relax the deterministic assumption: *actions are NOT deterministic*. 

The transition model can no longer be described by deterministic functions. If the agent is in a certain state and takes an action, the next state is only known in probability. The transition model now generates a *probability distribution* over the possible next states: $P(s' | s, a)$.

If we represent this as a directed graph:
- Each *node* is a state.
- Each *arc* represents an action/transition.

#note()[
  In this way, we can effectively capture and model the *uncertainty* of the real world.
]

In deterministic planning, the resolution is a simple *sequence of actions* (a plan). But in this case, since we are not sure about the exact effect of every single action, a static sequence will fail. 

Therefore, the real resolution is not a plan, but a *Policy* ($pi$). A policy dictates what action to take in *any* given state. The agent must constantly check the current state (feedback) before taking an action, because the current state is not calculated solely by the previous actions, but influenced by randomness.

To solve these types of problems, we typically use *Markov Decision Processes (MDP)*.

= Path Search Algorithms

== The A\* Algorithm

The goal of A\* (A-star) is to find a path that satisfies two main criteria:
1. It must bring the agent to the goal state.
2. It must minimize a specific cost function (e.g., distance, time, energy).

A\* is an informed search algorithm that searches among different possibilities by expanding the frontier on the nodes that minimize a specific evaluation function $f(n)$. Unlike the standard Breadth-First Search (BFS), A\* uses both the accumulated cost and an estimate of the remaining cost:

$ f(n) = g(n) + h(n) $

Where:
- $g(n)$: The current exact cost to arrive at node $n$ from the start.
- $h(n)$: The *heuristic*, which is the estimated cost to arrive at the goal from node $n$.

== Heuristics: Admissibility and Consistency

To guarantee that A\* finds the optimal solution, the heuristic must possess certain mathematical properties.

#theorem(title: "Admissibility")[
  The heuristic should always be *optimistic*. This means it must *never overestimate* the true cost to reach the goal. 
  $ h(n) <= h^*(n) $
  where $h^*(n)$ is the true optimal cost from $n$ to the goal.
]

*State Space vs. Search Tree:*
It is a very important distinction to make when visualizing the algorithm:
- *On the left (State Space):* We have the actual states of the environment. We cannot have duplicate states here.
- *On the right (Search Tree/Trace):* We have the trace of the algorithm solving the problem. Here, we can have multiple copies (nodes) representing the same state reached via different paths.

This distinction introduces the need for *pruning* (keeping a "closed list" of visited states so we don't explore them again). However, pruning introduces a risk: if we discard a path to a state, we might miss the optimal path.

#theorem(title: "Consistency")[
  A heuristic is consistent if, for every node $n$ and every successor $n'$ generated by an action $a$, the estimated cost of reaching the goal from $n$ is no greater than the step cost of getting to $n'$ plus the estimated cost from $n'$ to the goal:
  $ h(n) <= c(n, a, n') + h(n') $
]

#warning(title: "Consistency and Pruning")[
  Consistency is a stronger condition (a generalization) of admissibility. 
  - If the heuristic is *consistent*, the algorithm will *always* find the optimal solution, even if we use a pruning rule (closed list).
  - If it is admissible but *not* consistent, applying a pruning rule risks missing the optimal solution.
]

A search algorithm like A\* typically provides strong mathematical guarantees:
1. *Completeness:* If there is a goal state and a valid path to it (a solution to the problem exists), the algorithm will eventually find it at some point.
2. *Optimality:* If it finds a solution, it is mathematically guaranteed to be the *optimal* solution.

#note()[
  These types of algorithms are still highly relevant in modern robotics precisely because of these strict mathematical guarantees.
]

= Advanced Solution Techniques

== Multi-Robot Path Planning

Multi-robot path planning involves computing the path (or multiple paths) that a fleet of robots should follow to complete a collective task. 

The core challenge is dictating the actions of the robots cooperatively. We want to give the robotic system the capability to dynamically or pre-emptively answer the question: *"Where to go next?"* while avoiding interference.

== Multi-Agent Path Finding (MAPF)

The objective of MAPF is to find optimal, *non-interfering* paths for multiple agents, each with a unique start and goal position, operating within a *known* environment.

*Formal MAPF Definition:*
- We have $k$ agents.
- Each agent has a specific *start location*.
- Each agent has a specific *goal location*.
- The *Environment* is represented as a set of nodes and edges, typically a graph $G = (V, E)$. This can be a linear graph, a 3D graph, etc., but most of the time it is represented as a grid map with obstacles (holes).

For each agent, we have to calculate a continuous path from start to goal without breaking, getting stuck, or colliding.

There are typically two main *objective functions* used to evaluate the quality of a MAPF solution:
1. *Sum of Costs (SOC):* The sum of the distances/times each robot has covered.
2. *Makespan:* Instead of the sum, we take the maximum. The cost is defined as the time at which the *last* robot completes its path (the maximum distance any single robot has covered). This treats the fleet of robots as a single cohesive subject and is often considered the more interesting objective function.

*Managing Conflicts:*
Obviously, we do not want conflicts. If we discretize the environment into cells, we can increment a time step ($t + 1$) for every action. This allows the system to check if the next action will result in a collision.

There are two basic types of conflicts (though more complex ones exist):
1. *Vertex Conflict:* Two robots attempt to occupy the exact same cell (node) at the exact same time step.
2. *Edge Conflict (Swapping):* Two robots attempt to traverse the exact same edge in opposite directions at the same time step (they want to swap places). 

#informally(title: "Kinematic and Safety Constraints")[
  Depending on the specific problem, certain movements might be restricted. For example, sometimes it is forbidden for agents to move "like a little train" (following each other immediately edge-by-edge without a time-step buffer). These are specific safety or kinematic constraints that must be integrated into the collision-checking logic.
]

== Conflict-Based Search (CBS)

Conflict-Based Search (CBS) is a popular, complete, and optimal algorithm for solving MAPF problems. Just like A\*, given enough time, it is guaranteed to find the optimal solution (non-interfering paths that minimize the chosen objective function). 

#warning(title: "Computational Cost")[
  The theoretical computational cost of CBS is very high. In order to guarantee the optimal solution, the algorithm might take an *exponential number of steps* in the worst-case scenario. It can be highly inefficient if there are massive bottlenecks. However, *in practice*, it works quite well and is remarkably efficient on average for most practical scenarios.
]

CBS operates by performing a *two-level search*:

1. *Low-Level Search:* Computes an optimal plan for each agent *individually*. It typically runs A\* on the grid for a single agent, trying to find the shortest path from start to goal while strictly obeying a specific set of constraints provided by the high level.
2. *High-Level Search:* Runs a Best-First Search (BFS) on a structure called the *Constraint Tree (CT)*. In this tree, each node represents a set of constraints that forbid specific agents from being at specific points (vertices or edges) at specific times. The low-level planner is called to find a solution that satisfies the constraints of the current high-level node.

=== The Constraint Tree (CT)

In the high-level search, a *CT Node* contains:
- *A set of constraints:* These dictate what the agents *cannot* do. At the root node, this set is completely empty (agents plan as if they are alone in the environment).
- *A Joint Plan:* A set of individual paths for all agents, computed by the low-level planner respecting the node's constraints.
- *A Cost:* The total cost of the joint plan (e.g., sum of costs), used to order the Best-First Search queue.

=== Node Expansion and Splitting Logic

When the high-level search selects a node to expand, it evaluates the joint plan:
- *No conflicts?* If the paths of all agents in the joint plan do not interfere, we are *Done*. The optimal solution has been found.
- *Conflict detected?* Suppose there is a vertex conflict between agent $a$ and agent $b$ on vertex $v$ at time $t$. The algorithm must resolve this by *splitting* the node (and thus splitting the "search universe" into two disjoint universes).

When a conflict $(a, b, v, t)$ occurs, CBS generates two new child nodes, each adding a new constraint to the parent's set:
1. *Child 1:* Adds the constraint "$a$ cannot occupy $v$ at time $t$". The low-level planner is re-run for agent $a$ to find a new path that respects this.
2. *Child 2:* Adds the constraint "$b$ cannot occupy $v$ at time $t$". The low-level planner is re-run for agent $b$ to find a new path that respects this.

By continually splitting universes upon finding conflicts and exploring the lowest-cost nodes first, CBS systematically guarantees finding the optimal collision-free joint plan.

#note()[
  Over the years, many improved versions and variants of CBS have been developed to speed up the search space exploration (e.g., ICBS, ECBS, CBSH), but the fundamental two-level structure remains the same.
]

== Configurable MAPF (C-MAPF)

Traditionally, MAPF assumes a static, strictly known environment. *Configurable MAPF (c-MAPF)* (or Co-design MAPF) introduces a new paradigm: what if we can move the robots, but *also* modify the graph that describes the environment?

In C-MAPF, we can modify the topology of the environment, not arbitrarily, but in specific, allowable parts. 
- We might have the ability to open or close doors, change the direction of one-way lanes, or add/remove specific edges.
- This introduces new *degrees of freedom*, but it is bound by a *budget* and physical constraints (e.g., you can only open up to 3 doors, or changing an edge costs a certain amount of energy/time).

*The core question becomes:* What is the best configuration of the environment to choose in order to minimize the routing cost of the robots? 

To solve this, we can try to *extend CBS* with this additional degree of freedom. The search algorithm must now branch not only on routing conflicts between robots, but also on the configuration choices of the topology. This is a very active and innovative area of research in robotic planning.

#import "template.typ": *

== Multi-Agent Pickup and Delivery (MAPD)

In a Multi-Agent Pickup and Delivery (MAPD) scenario, we have an environment populated by multiple agents operating in *discrete time*. At each time step, an agent can either move to an adjacent vertex or stay at its current vertex. 

Unlike standard MAPF, the system must process a dynamic set of *Tasks*. Each task specifies:
- A pickup vertex $s_i$
- A delivery (goal) vertex $g_i$

Crucially, these tasks arrive dynamically at runtime (in a continuous stream $T$). Because we do not have the full specification of all tasks in advance, we cannot solve the entire problem offline before execution. Instead, we must solve it *online*.

#informally(title: "Online Algorithms")[
  Using an online algorithm means that the system must continuously track the state of what is happening on the network and react dynamically. The problem continuously unfolds at the exact same time the agents are executing their previously assigned tasks.
]

To manage this ongoing execution, the system must track the state of each agent:
- *Free agents:* Agents that currently have no task assigned and are available.
- *Busy agents:* Agents that are actively executing an assigned task.

#note()[
  Conceptually, MAPD can be viewed as a further generalization of MAPF (and c-MAPF), adding the complexity of dynamic task assignment and ongoing, infinite-horizon execution.
]

== Solving MAPD Problems: Token Passing

While we won't dive into the low-level details of specific algorithms, we can understand the high-level logic used to solve MAPD through approaches like *Token Passing*.

Token Passing is a decentralized-style algorithm that iteratively assigns free agents to unassigned tasks. It maintains a partial, safe solution—a set of synchronized, collision-free paths for the currently planned agents—known as the *Token*.

*How it operates:*
1. *Task Eligibility:* A task is considered *eligible* to be assigned only if its pickup and delivery locations are NOT the final destinations of any other path currently stored in the Token.
2. *Path Assignment:* Once a free agent is paired with an eligible task, the system computes a collision-free path for it (first to the pickup location, then to the delivery location). 
3. *Path Computation:* For computing this specific path, we can act modularly and use *any* compatible pathfinding algorithm we want (e.g., A\* or CBS), as long as it respects the constraints of the paths already reserved in the Token.
4. *Updating the Token:* The newly computed path is added to the Token, and the agent's status changes from free to busy.

#warning(title: "The Core Challenge: Reactivity")[
  The defining characteristic of solving MAPD is the absolute need to *react*. We have no advanced specification of the future. The planner must constantly adapt to new task specifications on the fly, ensuring that newly generated paths seamlessly integrate into the Token without causing collisions with ongoing operations.
]

== Discussion

Can we do deterministic planning with an LLM?


