#import "../template.typ": *

In the immage the probability of the robot that follow the red arch to arrive at blue arrow it's impossibile.

== Velocity Model evaluation

The rotation error is an error around an angula velocity, i assume that this error has a mean of zero and follow a Gaussian distribution.
For each componets i will give a score.....


#example()[
  The sigma is a linear combination of a square of the velocity and the square of the angular velocity, this is because the error is bigger when the robot move faster and when it rotate faster.

  the gamma is just drift, the noise is sampled from a Gaussian distribution with mean zero and variance one, the error is the sum of the drift and the noise multiplied by the sigma.

  From this process i obtein three parameter $v, omega, gamma$. The new pose $s_t$ is genereted given the parameters into a kinematic model, the new pose is the old pose plus the error generated by the noise.
]

== Robot Perception

Same intiution as motion models. Perception model need to shape uncertanty in a different way, because sensor generate noise not only in a gassian way but they have a more sistemetic error generation. The model is used to represent (and compute):
$
  p(z_t | s_t)
$
We are going consider one class of sensore extremely popular, the range finder sensors. A rage finder is a sensor that have laser and it measure the distance of the object in front of it. The sensor measure the time of flight, given time of flight and the speed of light we can compute the distance of the object.
The rage finder inject energy in the system and wait for the echo (a sonar it's a type of the range finder sensor).

The environment influence the sensor measurement (map).

We refine the model distribution to include the map of the environment $mr(m)$ in the given knowledge of the robot:
$
  p(z_t | s_t, mr(m))
$
the $m$ contrbiutes to the explaination of the measurement
#note()[
  We are going to assume that the map is *discrete*
]
We can have location-based map, each corrispond to a specific location of the environment and reporting a set of features. Very different from a feature based map, where the map is a set of features and the robot need to find the feature in the environment. The location-based map is more simple to use but it's less flexible, the feature-based map is more flexible but it's more complex to use: For each points in the space i will say something about it.

For every point in the space i will say if it's occupied or not. I can also give the probability of the point to be occupied, this is called probabilistic *occupancy grid*: Each cell $c$ is represented by the coordinates of its center $x_c$, $y_c$ and reports its occupancy value $o(c)$:
- $o(c) == 1$ occopied by an obstacle
- $o(c) == 0$ free space
- $o(c)$: probability of being occupied by an obstacle

I can also add some additional information to the map, for example the color of the cell, the type of the cell, etc.

=== Range finder

Is a sensor that produce a scan of measurement, the scan is a set of measurement:
$
  z = (z_1, z_2, ..., z_K)
$
where $n$ is the number of measurement. Each measurement $z_i$ is the distance of the nearest object in the direction $i$.
#note()[
  In general if i take a measurement $z_i$ it can depends from the previous measurement $z_{i-1}$, if i don't know the pose of the robot and the map of the environment. In this case $z_i$ help us to understand the pose of the robot and the map of the environment, so $z_i$ is not independent from $z_{i-1}$.
]
All the measurement are conditionally indipendent if a know the map and the current pose (the map and the pose can explain each measurement, so they are indipendent from each other):
$
  p(z | s, mr(m)) = product_(i=1}^K p(z_i | s_t, mr(m))
$
The interior probability $p(z_i | s_t, mr(m))$ is the likelihood of the sensor in a specific direction, given the pose of the robot and the map of the environment. Its the perception model, it explains the single measurement.
#note()[
  The perception model tell us the limits of the sensor, for example if the sensor can measure up to 10 meters, the perception model will tell us that the probability of measuring a distance greater than 10 meters is zero.
]
We are going to consider two different model, two differen way to explain the measurement of the sensor:
- The *beam model*: It explain the measurement of the sensor given the pose of the robot and the map of the environment.
- The *likelihood field model*: It explain the measurement of the sensor given the pose of the robot and the map of the environment, but it consider also the uncertainty of the measurement.

== Beam model

It reasons about the beam that came from the sensor, hit an obstacle, and come back to the robot.
Suppose thath we have the pose and the map at time $t$, suppose that the robot its looks in front of it, can we compute a guess of the distance that is going to measure? Yes, it the same as the *forward kinematics* (given the current pose and the control action, i compute the next state).

We need to perform a *ray tracing* operation, it's the computation equivalent of the range sensor. I call the distance measurement $z^*$, it's the distance of the nearest object in the direction of the sensor. The operations to compute that its called *ray casting*: i sumulate the beam on the map and look where it hits, if i'm in a ideal situation, the measurement of the sensor is going to be $z^*$. In a real situation, the measurement of the sensor is not going to be $z^*$, but it's going to be a noisy version of $z^*$ (it's close to it), so we need to consider the noise of the sensor.
The noise is caused by surprise that can occuper form the travel of the beam. If we are good enought to list all the surprise that can occuper, we can achive a good guess of the measurement of the sensor.

The noise source can be caused by:
- Every sensor has a intrisic noise, it's the noise that is caused by the sensor itself, the measurement it's something near $z^*$.

- Unexpected objects entering in the FOv: obstacles that are not included in $m$, might appear and intercept the beam before it heats the obstacle on the map.
  #note()[
    It depends on the distance of the obstacle $z^*$, if $z^*$ is higher its much probable that an unexpected object can enter in the FOV.
  ]

- Failure of the sensor: the ostacle is missed, hits a black or transparent surface. The sensor report $z_"max"$. When the sensor its not capable to measure the distance it report the maximum distance that it can measure, this is a failure of the sensor.

- Random measurements: the sensor report a random measurement, this is a failure of the sensor. For example sensors cross-talk, the measurement of a sensor can be influenced by the measurement of another sensor, this is a failure of the sensor.

The *measurment noise* can be modeled as a *gaussian distribution* centered in $z^*$. This is the $z^*$ (random variabile) plus a noise gaussian with mean zero and variance $sigma^2$. If i obstacle is $5$ meters away we have $0$ probability that the sensor report $10$ meters, but we have a non zero probability that the sensor report $5.1$ meters, this is the noise of the sensor.

The Unexpected objects can be modeled as a *exponential distribution* with parameter $lambda$. The probability of measuring a distance $z$ is $lambda e^(-lambda z)$, this is the probability that an unexpected object enter in the FOV at distance $z$.

The failure of the sensor can be modeled as a *point mass distribution* centered in $z_"max"$. The probability of measuring $z_"max"$ is $p_"max"$, this is the probability that the sensor fail to measure the distance.

The random measurements can be modeled as a *uniform distribution* between $0$ and $z_"max"$. The probability of measuring a distance $z$ is $1/(z_"max")$, this is the probability that the sensor report a random measurement.

The final shape is a linear combination of the four distribution. Wich models the probability of measuring a distance $z$ given the pose of the robot and the map of the environment: $p(z_i | s_t, m)$

== Likelihood field model

//da riguardare


