#import "../template.typ": *

In the immage the probability of the robot that follow the red arch to arrive at blue arrow it's impossibile.

== Velocity Model evaluation

The rotation error is an error around an angula velocity, i assume that this error has a mean of zero and follow a Gaussian distribution.
For each componets i will give a score.....


#example()[
  The sigma is a linear combination of a square of the velocity and the square of the angular velocity, this is because the error is bigger when the robot move faster and when it rotate faster.

  the gamma is just drift, the noise is sampled from a Gaussian distribution with mean zero and variance one, the error is the sum of the drift and the noise multiplied by the sigma.

  From this process i obtein three parameter $v, omega, gamma$. The new pose $s_t$ is genereted given the parameters into a kinematic model, the new pose is the old pose plus the error generated by the noise.
]

== Robot Perception

Same intiution as motion models. Perception model need to shape uncertanty in a different way, because sensor generate noise not only in a gassian way but they have a more sistemetic error generation. The model is used to represent (and compute):
$
  p(z_t | s_t)
$
We are going consider one class of sensore extremely popular, the range finder sensors. A rage finder is a sensor that have laser and it measure the distance of the object in front of it. The sensor measure the time of flight, given time of flight and the speed of light we can compute the distance of the object.
The rage finder inject energy in the system and wait for the echo (a sonar it's a type of the range finder sensor).

The environment influence the sensor measurement (map).

We refine the model distribution to include the map of the environment $mr(m)$ in the given knowledge of the robot:
$
  p(z_t | s_t, mr(m))
$
the $m$ contrbiutes to the explaination of the measurement
#note()[
  We are going to assume that the map is *discrete*
]
We can have location-based map, each corrispond to a specific location of the environment and reporting a set of features. Very different from a feature based map, where the map is a set of features and the robot need to find the feature in the environment. The location-based map is more simple to use but it's less flexible, the feature-based map is more flexible but it's more complex to use: For each points in the space i will say something about it.

For every point in the space i will say if it's occupied or not. I can also give the probability of the point to be occupied, this is called probabilistic *occupancy grid*: Each cell $c$ is represented by the coordinates of its center $x_c$, $y_c$ and reports its occupancy value $o(c)$:
- $o(c) == 1$ occopied by an obstacle
- $o(c) == 0$ free space
- $o(c)$: probability of being occupied by an obstacle

I can also add some additional information to the map, for example the color of the cell, the type of the cell, etc.

=== Range finder

Is a sensor that produce a scan of measurement, the scan is a set of measurement:
$
  z = (z_1, z_2, ..., z_K)
$
where $n$ is the number of measurement. Each measurement $z_i$ is the distance of the nearest object in the direction $i$.
#note()[
  In general if i take a measurement $z_i$ it can depends from the previous measurement $z_{i-1}$, if i don't know the pose of the robot and the map of the environment. In this case $z_i$ help us to understand the pose of the robot and the map of the environment, so $z_i$ is not independent from $z_{i-1}$.
]
All the measurement are conditionally indipendent if a know the map and the current pose (the map and the pose can explain each measurement, so they are indipendent from each other):
$
  p(z | s, mr(m)) = product_(i=1}^K p(z_i | s_t, mr(m))
$
The interior probability $p(z_i | s_t, mr(m))$ is the likelihood of the sensor in a specific direction, given the pose of the robot and the map of the environment. Its the perception model, it explains the single measurement.
#note()[
  The perception model tell us the limits of the sensor, for example if the sensor can measure up to 10 meters, the perception model will tell us that the probability of measuring a distance greater than 10 meters is zero.
]
We are going to consider two different model, two differen way to explain the measurement of the sensor:
- The *beam model*: It explain the measurement of the sensor given the pose of the robot and the map of the environment.
- The *likelihood field model*: It explain the measurement of the sensor given the pose of the robot and the map of the environment, but it consider also the uncertainty of the measurement.

== Beam model

It reasons about the beam that came from the sensor, hit an obstacle, and come back to the robot.
Suppose thath we have the pose and the map at time $t$, suppose that the robot its looks in front of it, can we compute a guess of the distance that is going to measure? Yes, it the same as the *forward kinematics* (given the current pose and the control action, i compute the next state).

We need to perform a *ray tracing* operation, it's the computation equivalent of the range sensor. I call the distance measurement $z^*$, it's the distance of the nearest object in the direction of the sensor. The operations to compute that its called *ray casting*: i sumulate the beam on the map and look where it hits, if i'm in a ideal situation, the measurement of the sensor is going to be $z^*$. In a real situation, the measurement of the sensor is not going to be $z^*$, but it's going to be a noisy version of $z^*$ (it's close to it), so we need to consider the noise of the sensor.
The noise is caused by surprise that can occuper form the travel of the beam. If we are good enought to list all the surprise that can occuper, we can achive a good guess of the measurement of the sensor.

The noise source can be caused by:
- Every sensor has a intrisic noise, it's the noise that is caused by the sensor itself, the measurement it's something near $z^*$.

- Unexpected objects entering in the FOv: obstacles that are not included in $m$, might appear and intercept the beam before it heats the obstacle on the map.
  #note()[
    It depends on the distance of the obstacle $z^*$, if $z^*$ is higher its much probable that an unexpected object can enter in the FOV.
  ]

- Failure of the sensor: the ostacle is missed, hits a black or transparent surface. The sensor report $z_"max"$. When the sensor its not capable to measure the distance it report the maximum distance that it can measure, this is a failure of the sensor.

- Random measurements: the sensor report a random measurement, this is a failure of the sensor. For example sensors cross-talk, the measurement of a sensor can be influenced by the measurement of another sensor, this is a failure of the sensor.

The *measurment noise* can be modeled as a *gaussian distribution* centered in $z^*$. This is the $z^*$ (random variabile) plus a noise gaussian with mean zero and variance $sigma^2$. If i obstacle is $5$ meters away we have $0$ probability that the sensor report $10$ meters, but we have a non zero probability that the sensor report $5.1$ meters, this is the noise of the sensor.

The Unexpected objects can be modeled as a *exponential distribution* with parameter $lambda$. The probability of measuring a distance $z$ is $lambda e^(-lambda z)$, this is the probability that an unexpected object enter in the FOV at distance $z$.

The failure of the sensor can be modeled as a *point mass distribution* centered in $z_"max"$. The probability of measuring $z_"max"$ is $p_"max"$, this is the probability that the sensor fail to measure the distance.

The random measurements can be modeled as a *uniform distribution* between $0$ and $z_"max"$. The probability of measuring a distance $z$ is $1/(z_"max")$, this is the probability that the sensor report a random measurement.

The final shape is a linear combination of the four distribution. Wich models the probability of measuring a distance $z$ given the pose of the robot and the map of the environment: $p(z_i | s_t, m)$

== Likelihood field model

//da riguardare


When something like an obstacle enter in the fov of the robot, the probability to get an higher mesurament than $z^*$ should be zero, at least the mesurament is lower than $z^*$. Measuring a larger value similar to $z^*$ should be less probable than measuring a smaller value. For that reason we have an exponential distribution.

== Likelihood field

We are not reasoning about the probability of the mesurament $z$ given the pose of the robot, but we are reasoning about the probability of the mesurament $z$ given the position of the obstacle.

The map is computed in this way:
- I don't care about the pose and orentation of the robot.
- I suppose that the robot sensor measures combine with his position and orientation give a mesurament $z$ (green dot)
- I need to compute how probable is to get that mesurament $z$ given the position of the nearest obstacle (the responsible for that mesurament).

=== Proprioceptive sensors

#informally()[
  it's something with come form the robot
]

An example it's the wheel encoder, that measure the rotation of the wheel, and from that we can compute the distance traveled by the robot.

Another sensor is the *IMU* (Internal Measurment Unit), it can measure the linear acceleration, angular velocity, and magnetic field stenght. Resturns linear acceleration and angular velocity, that can be used to compute the pose of the robot (quaternions, roll, pitch, yaw).

We can also have system health sensors, that measure the temperature of the robot, the battery level, etc.

=== Exteroceptive sensors

#informally()[
  it's something with come from the environment
]

An example it's the sonar, that measure the distance to the nearest obstacle in a certain direction.
#note()[
  They have a wide fov and short range. They not suitable for localization feature in the environment or builiding a map of the environment, but they are good for obstacle avoidance (tehy not tell us were the obstacle is).
]

If the robot has a constrait on the valocity that we can apply to the robot (the robot can move anywhere in the space, but with a contstrain on the way to reach that position), its a non holominic robot. the robot pi it's a holominic robot

Also *Laser RangeFinder* are in this category. They measure distances along a set of directions, very often along a plane. They are more expencive than the sonar, but they are more accurate and have a longer range. They are suitable for localization and mapping, but they are not good for obstacle avoidance (they tell us were the obstacle is, but they not tell us how to avoid it).


There are also *3d rangefinder*. They give us a 3d point cloud of the environment, for example a set of points coordinates referred to a reference frame placed on the sensor.

ALso *cameras* are in this category. They give us a 2d image of the environment, that we can use to extract features, or to build a 3d model of the environment. We can also have bumpers, they are used to determine if the robot it's toching something, (they are like a binary switch).

== Bayer Filter Implementation

In reality we can only use a continuois bias filter where the belief its a simplify version (like a function).

the first part is the perceptional model, the secon part is the motion model. We need a way to compute that probability, then we can only need to integrate them.

if the two part are very complex form , solving the prediction step and the correction step can be very complex. We introduce the *Kalmn Filter*: I assume that motion and sensing model are very simple, enough that the prediction step becomes analytically tractable, we will get a formula to solve the integral.

=== Gaussian distribution

we can use a Gaussian distribution, a gaussian can represent a simple belif (with only a local maximum), and it can be easily manipulated mathematically.

If we represent the belief as a Gaussian, with two numbers we can represent the belief over a milion of possible states.

Kalmar filter has a lot of assumptions:

1. The belief is represented as a Gaussian distribution $"Bell"(s_0) tilde N(mu_0, sigma_0^2)$. We can't choose the form of the prior, but we can *choose the parameters* of the prior (the mean and the variance). Initially the parameters are set to represent a very uncertain belief (a Gaussian with a very large variance).

2. The *motion model* is a linera trasformation plus a Gaussian noise.
  #note()[
    It's a very strong assumption, because motion models are often non linear. In the reality it's not like that.
  ]
  The next pose of the robot $s_t$ it's a linear combination of the previous pose $s_{t-1}$ and the control input $u_t$, plus a Gaussian noise with zero mean and covariance $R_t$:
  $
    s_t = A_t s_(t-1) + B_t u_t + epsilon_t tilde N(0, r_t)
  $
  where $A_t$ and $B_t$ are matrices that depend on the time step $t$.\
  The all thing are rappresented with a Gaussian with mean $A_t s_(t-1) + b_t u_t$ and variance $R_t$ (the noise variance).

3. The *perception model* is a linear trasformation plus a Gaussian noise.
  #note()[
    It's a very strong assumption, because perception models are often non linear. In the reality it's not like that.
  ]
  The mesurament $z_t$ it's a linear combination of the pose of the robot $s_t$, plus a Gaussian noise with zero mean and covariance $Q_t$:
  $
    z_t = C_t s_t + delta_t tilde N(0, q_t)
  $
  where $C_t$ is a matrix that depend on the time step $t$.\
  The all thing are rappresented with a Gaussian with mean $C_t s_t$ and variance $q_t$ (the noise variance).

=== Kalman Filter

Kalmar filter now become a trivial linear algebra problem in repsect of intefral, we can solve the prediction step and the correction step with a simple formula.

THe belif filter admit a solution that we can compute basic some matric moltiplication. The final belif it's also a Gaussian distribution, with mean and variance that we can compute with a simple formula. The result change the shape from the prior, but it's still a Gaussian distribution.

== Extended Kalman Filter

The EKF relaxes the assumption of linearity, we can have a non linear motion model and a non linear perception model.

The first assumption remain, the prior belief is represented as a Gaussian distribution.But:

1. The motion model it a non linear trasformation plus a Gaussian noise. $g$ its a non linear function:
$
  S_t = g(s_(t-1), u_t) + epsilon_t tilde N(0, r_t)
$
#warning()[
  In this case we can't model the distribution probability $p(s_t | u_t, s_(t-1))$ as a gaussian distribution, because the non linear function $g$ can change the shape of the distribution.
]
2. The perception model it a non linear trasformation plus a Gaussian noise. $h$ its a non linear function:
$
  z_t = h(s_t) + delta_t tilde N(0, q_t)
$

Singe $g$ and $h$ are non linear, the bayes filter does not admit an analytical solution. We need to *linearize* g and h around the points that we want to evaluete the function consider in the filter. In this case:
- Linearize $g$ around $g(s_(t-1), u_t)$
- Linearize $h$ around $h(s_t)$

When we linearize stuff we need to compute the derivative of the function, meaning that the math become more complex.

*Unicycle model*: its when we describe the motion of a robot with two wheels, we can use the EKF to estimate the pose of the robot given the control input and the mesurament.


#example()[

  //ricontrolalre
  If i have a differential drive robot, if we have a direction $v$ and linear velocity $w$, we need to convert $v$ and $w$ to an angular velocity for each wheel.

  We suppose that robot have a gps sensor that tell the $x$ and $y$ of the robot in the plane.

  Given $v$ and $w$ (the current pose) we need to compute the ideal next pose. THis is a non linear function (cosine and sine). The linear sensing model is a real pose + a noise gaussian.

  In the example the sensing noise and the motion noise are represented as a matrix. Each dimension of the matrix affects a specific coordinates on the plane (x,y, $theta$).

  At each temporal step an hardcoded control action will be applied to the robot. The robot go straight, go left and curve right for a certain amount of time.

  in the simulation loop i compute the true coordinates of the robot (it don't know them). They are compute as the equation in the previous slide.

  The robot its going to recive a the real measuremtn plut a gaussian noise (we simulate the mesurament that come from the gps sensor).

  Dead reckoning: i compute the current position of the robot. It assume an ideal enviroment (no slippage) and we are not considering the gps mesurament (only the internal mesurament will be considered).
  #note()[
    This exstimation continue to diverge form the real position of the robot, because we are not considering the gps mesurament, and we are assuming an ideal enviroment (no slippage). The error accumulate over time, and the estimation become more and more wrong.
  ]
  The blue curve its what we get when we combine the dead reckoning with the gps mesurament, using the EKF. The estimation is very close to the real position of the robot, because we are considering the gps mesurament, and we are not assuming an ideal enviroment (we are considering the noise).

]

#warning()[
  The previus example show usa that we can't realay only on the internal mesurament of the robot, because the error accumulate over time. We need to combine the internal mesurament with the external mesurament, even if they are noisy, to get a good estimation of the pose of the robot.
]

// Jack's notes

== Likelihood fields (End-Point Sensor Models)

//TODO: GRAPH NEEDS CORRECTION

Unexpected obstacles are more probable to generate small sensor readings. This is because the longer the sensor beam, the larger the probability of encountering an obstacle along its path. This is why the probability distribution graph for unexpected objects initially descends (exponentially) and then suddenly drops at $z^*$.

Remember that the likelihood field is a different perspective on sensor models compared to ray-casting. Instead of tracing a beam to find the exact intersection, it uses an end-point model.

#informally[
  Basically, if I measure a "hit" (a reading from a sensor like a lidar), I know that there must be an obstacle responsible for it in the environment. To explain the hit, we simply consider the closest obstacle in our map, and we give that closest obstacle the responsibility of generating the hit. So, we calculate the Euclidean distance from the hit point to the obstacles in the map and we take the closest one.
]

#example[
  If I had a hit on the right of a mapped cube, I calculate the distances from the hit to all mapped objects. The cube will be the closest obstacle, so it is considered the responsible object for the hit.
]

Black areas in the likelihood map = no robot can have a hit in this position (e.g., inside solid obstacles).

#note[
  These probabilistic models are essential for the most common sensors used in robotics, such as laser rangefinders.
]

= Sensors

== Proprioceptive sensors

Robotics introspection, which basically measures values internal to the robot itself.

#note(title: "Debate")[
  Are the wheels of the robot considered part of the robot or the environment? 
  *Yes*, they are part of the robot, so measuring their movement is proprioception.
]

=== Encoders (Odometry)
These sensors measure the angular position and velocity of the wheels. 
They can be optical, or use a magnet (magnetic encoders). They are used for low-level motor control and to infer the pose (position and orientation) of the robot through odometry, providing a first, albeit noisy, measurement of movement.

#warning[
  Odometry measurements should not be blindly trusted over long distances: they work assuming that there is no noise (no wheel slip, exact wheel diameter). Over time, the measurements accumulate errors and become very noisy.
]

If I just obtain the position using odometry (relying only on motion models), I keep moving while accumulating all the previous errors (a phenomenon called *dead reckoning*). Therefore, my final pose measurement will be awful and significantly drift from reality.

=== Inertial Measurement Unit (IMU)
Based on accelerometers and gyroscopes, an IMU returns linear accelerations, angular velocities, and orientation (often represented as quaternions or Euler angles). 
They are frequently fused with encoders to mitigate dead reckoning drift (e.g., IMUs provide good rotational data where wheels might slip).

=== System health diagnostics
Monitors internal states like temperature or battery levels. Essential for power management, fault detection, and mission autonomy.

== Exteroceptive sensors 

Exteroceptive sensors measure information from the robot's surrounding environment.

=== Sonar (Ultrasonic Sensors)
They return the distance to the closest obstacle in a given direction using sound waves.
They are very noisy and very inexpensive. This makes them very good for simple reactive tasks like obstacle avoidance, but not ideal for localizing complex features in the environment or building high-resolution maps.

#note(title: "Kinematic Constraints")[
  When avoiding obstacles, we must consider the robot's kinematics. A robot might be non-holonomic:
  - *Ackermann steering*: The motion model that standard cars use. The direction is constrained (the front wheels pivot), which is why we have to do specific maneuvers (like parallel parking).
  - *Non-holonomic robots*: Robots with kinematic constraints. The robot can theoretically reach any position in space, but it cannot move on any arbitrary trajectory (e.g., a car cannot instantly move sideways).
  - *Holonomic robots*: By contrast, these can move instantaneously in any direction (like robots with omni-wheels).
]

=== Laser rangefinder (Lidar)
Uses light beams to measure distances. Much more accurate and faster than sonars, but traditionally much more expensive. Excellent for mapping and localization.

=== 3D Range Finders (3D Lidar)
They are a 3D version of laser rangefinders, reading multiple beams across a solid angle. The value returned is represented by a point cloud. Very expensive, and processing the massive amount of data requires large computational power.

=== GPS (Global Positioning System)
Returns the global latitude and longitude of the robot. Works outdoors.
The main problem is that in order to get a reliable reading, the receiver needs a clear line of sight to multiple satellites. This is not always guaranteed (e.g., robots surrounded by high buildings in "urban canyons", irregular walls, tree canopies, etc.).

=== Cameras and Other Sensors
- *Cameras (RGB)*: Provide rich visual data.
- *Depth Cameras (RGB-D)*: Provide both an image and a depth map.
- *Contact sensors*: Bumpers that detect physical collision with an object.

= Localization and Filters

== Gaussian Filters and Bayes Filter Implementation

We need a continuous Bayes filter to represent the probability distribution (belief) of a robot's pose in a continuous environment.
It tells us how to use motion models and sensing models to recursively propagate a belief state over time.

To do that, we need to mathematically define such models. Specifically, we must compute the integral in the prediction step (incorporating the motion model) and apply Bayes' rule in the correction step

== Kalman Filter

#informally[
  The Kalman Filter is a specific implementation of the Bayes filter. We pretend that the motion and sensing models are the simplest possible ones (linear). This is an approximation of the real world, but it gives priority to mathematical tractability. A way to elegantly solve the integral.
]

=== Gaussian Distribution
We use Gaussian (Normal) distributions to model noise. 
Gaussians have unique mathematical properties, making them the "black hole" of distributions (due to the Central Limit Theorem). However, they have limits: they are unimodal (can only represent a single hypothesis/peak).

=== Three Key Assumptions:

1. *Gaussian Prior*: My initial belief must be a Gaussian. I cannot choose an arbitrary shape for the prior, but I can choose its mean and variance: 
   $ "Bel"(x_0) tilde cal(N)(mu_0, Sigma_0) $
   If the initial state is totally unknown, I will choose a very wide Gaussian distribution (huge variance). If the initial state is perfectly known, I use a very narrow Gaussian.

2. *Linear Motion Model + Gaussian Noise*: The transition from the previous pose to the next pose $x_t$ is a linear transformation plus some added noise. We replace complex kinematics with the simplest function: a line.

3. *Linear Perception Model + Gaussian Noise*: The measurement $z_t$ is a linear transformation of the state plus Gaussian noise. In reality, this is rarely true, but we assume it to simplify things.

*Conclusion*: With these three assumptions, the Bayes filter integral can be solved analytically. Prediction and correction steps become simple linear algebra (matrix multiplications), and the output belief is *always* strictly a Gaussian. We preserve the shape of the probability function forever.

== Extended Kalman Filter (EKF)

The EKF is historically one of the most used systems for localization in robotics.

#warning[
  The problem with the standard Kalman Filter was the linearity assumption. In the real world, robot kinematics and sensor geometries are *almost never* linear!
]

The Motion model is a non-linear transformation: instead of having linear matrices, we replace that part with a non-linear function $g$. 

Because the functions are non-linear, pushing a Gaussian through them would distort its shape—we wouldn't know how the conditional probability is shaped, and it probably wouldn't be a Gaussian anymore.

#informally[
  *What do we do when we have something that is not linear? We linearize it.* \
  Consider the non-linear function $g$. We linearize it locally around the current mean point (our best estimate) of the filter. 
]

This is called linearization, and it is achieved using a first-order Taylor expansion. To do this, I need to compute the derivatives of the functions with respect to the state variables. These matrices of partial derivatives are called *Jacobians*.

In short: the EKF pretends that the world is linear, but only locally in a small region around the robot's current estimated position.

#example(title: "Unicycle Model Example")[
  A common non-linear motion model is the Unicycle model, described by a linear velocity $v$ and an angular velocity $omega$. It is called this because it behaves like a circus unicycle. This introduces trigonometric functions (sine and cosine), making the model strictly non-linear.
]

I cannot rely only on the motion model (as seen in the demo example, dead reckoning causes the uncertainty to grow to infinity). The EKF prediction step uses the unicycle model to move the belief, but we absolutely need the correction step (using exteroceptive sensors) to shrink the uncertainty back down.
