#import "../template.typ": *

= Robot Perception

Explain how the sensor arrives at a specific measurement, considering the sources of uncertainty that might affect it. 

#note()[
  Sensors generate noise not only following a Gaussian distribution, but they also exhibit a more systematic error generation. The sources of uncertainties modeled should be consistent with reality.
]

There are systematic ways of modeling noise beyond simply assuming a Gaussian distribution. The noise generated by a sensor is typically structured into various distinct components.

We must be very careful about how we model this noise.
The sensor model is fundamentally a conditional probability: 
$ p(z_t | s_t) $

We will focus on one specific class of sensors: range finders.

#note()[
  A range finder is a laser device that shoots beams in different directions. When the laser hits an obstacle and reflects back, the sensor measures the time of flight (the time between emission and return) to determine the distance and orientation of the obstacle.
]

#warning()[
  Is the robot's position the only factor that influences its perception of the environment? NO
]

We need to introduce another critical element that influences the perception of a range finder: the *environment*, which we will formalize as the *map*.

In our model definition, we must include the map $m$ as part of our prior knowledge:

$ p(z_t | s_t, m) $

#note()[
  This assumption is not always true for modern robots, which often do not know the map beforehand and must build it incrementally (SLAM). However, for this theoretical context, we assume the map is known.
]

#note()[
  The map is typically a *discrete* representation of the environment.
]

If the robot does not know its position within this map, it faces the *localization problem*: "Where am I in the map?"

The map provides the necessary context to explain why the robot collected a specific set of measurements.

*Location-based map:* A location-based map (a very popular implementation in mobile robotics is the *Occupancy grid map*) is essentially a collection of elements, each corresponding to a specific location in the environment and reporting a set of features. This is often referred to as a _volumetric_ representation, distinguishing it from a feature-based map. A location-based map acts as a comprehensive grid where, for each possible small area (or cell) of the space, information regarding obstacle occupancy is provided (e.g., a binary "yes/no" or the continuous probability of an obstacle being present).

#note()[
  The location-based map is simpler to use but less flexible; conversely, a feature-based map is more flexible but more complex to use.
]

If the space is modeled as a discrete grid (similar to pixels covering a 2D plane area), we refer to these elements as cells. A cell $c$ can be represented by coordinates $x_c, y_c$, and its occupancy value is denoted as $o(c)$:

- $o(c) = 1$: Cell is occupied by an obstacle (black spot).
- $o(c) = 0$: Cell is free from obstacles (white spot).
- $0 < o(c) < 1$: The probability that the cell is occupied by an obstacle.

#align(center)[
  #image("/assets/occupancy_grid_map.png", width: 60%)
]

#note()[
  Besides occupancy information, maps can also contain semantic information, characterizing the space by identifying features like "door", "kitchen", or the color of the cell, for example.
]

== Range Finders

They are a specific type of sensor that produces a scan $z$ (consider the $2D$ case) composed of $K$ individual measurements:

$ z = {z_1, ..., z_K} $

Each measurement $z_i$ represents the distance from the robot's center to the *nearest* obstacle along a beam or a cone at a given heading.

#align(center)[
  #image("/assets/range_finder.png", width: 40%)
]

#warning()[
  Are the individual measurements dependent or independent?
]

If the robot's position in the map is unknown, the measurements are *dependent*: there is a high correlation between adjacent readings. 
However, given the map $m$ and the current pose $s_t$, all measurements are considered *conditionally independent*.
Since the map and the current pose fully describe the state, we can calculate the probability of an entire scan as the product of the likelihoods of individual measurements:

$ p(z | s_t, m) = product_(i = 1)^K p(z_i | s_t, m) $

This is the *perception model* of the sensor, which explains the single measurement and essentially quantifies the reliability and accuracy of the sensor.

#informally()[
  The perception model tells us the limits of the sensor. For example, if the sensor can measure up to 10 meters, the perception model will tell us that the probability of measuring a distance greater than 10 meters is zero.
]

There are two primary basic models to explain how measurements are delivered by the sensor:

- Beam model: it explains the measurement of the sensor given the pose of the robot and the map of the environment.

- Likelihood fields (Scan model): it explains the measurement of the sensor given the pose of the robot and the map of the environment, but it also considers the uncertainty of the measurement.

=== Beam Model

#informally()[
  The beam model reasons about what happened along the beam that generated the measurement. Let's analyze the physical journey of a laser beam starting from the robot and returning to it.
]

Given $x_t$ (robot's current pose), the map $m$, and the heading of the beam ($i$), we can compute the expected, ideal distance measurement, denoted as $z^*$.

#note()[
  This is computed using an exact model, sharing the same philosophy as *forward kinematics* (given the current pose and the control action, I compute the next state).
]

We calculate $z^*$ via *ray casting/ray tracing*: we simulate the beam within the map and determine mathematically where it hits.

#align(center)[
  #image("/assets/ray_tracing.png", width: 45%)
]

In an ideal, _noise-free_ scenario with zero uncertainty, the sensor would return exactly $z^*$. However, reality is imperfect. The actual measurement will likely be close to $z^*$, but affected by noise. This noise is caused by physical phenomena and "surprises" that occur during the beam's flight. 

#warning()[
  If we can comprehensively list all these potential interfering factors, we can build a probabilistic model to explain the measurements.
]

#informally()[
  What would affect this ideal quantity $z^*$? (This is where the reasoning about the beam happens). What causes the gap between simulation and reality? 
]

- *Measurement noise (Timing precision):* Range finders measure time-of-flight. Since sensors cannot have 100% accuracy, it will measure something that is *around* $z^*$ and not precisely $z^*$. Every sensor has an intrinsic noise.

- *Unexpected objects entering the FOV (Dynamic obstacles):* Obstacles that are not included in $m$ might appear and intercept the beam *before* it hits the expected mapped obstacle (e.g., people walking nearby the robot). This results in a shorter reading.

#note()[
  The greater the expected distance ($z^*$), the higher the probability that an unexpected object will intersect the beam's path.
]

- *Failures:* The obstacle is missed. This happens if the beam hits a black or transparent surface, if bright sunlight tampers with the beam, or if the obstacle is simply beyond the sensor's range. The sensor typically reports $z_"MAX"$ (maximum range).

- *Random measurements:* Random noise that cannot be ascribed to the previous ones (e.g., sensor crosstalk or phantom reflections).

Each of these four phenomena is modeled mathematically by a specific probability density function:

1. *Measurement noise:* Gaussian distribution centered at the true distance $z^*$. This is the $z^*$ (random variable) plus a Gaussian noise with zero mean and variance $sigma^2$. If an obstacle is $5$ meters away, we have $0$ probability that the sensor reports $10$ meters, but we have a non-zero probability that the sensor reports $5.1$ meters; this is the noise of the sensor.

#align(center)[
  #image("/assets/measurement_noise.png", width: 50%)
]

2. *Unexpected obstacles:* Exponential distribution (the probability of hitting an unmapped object decreases as distance increases) with parameter $lambda$. The probability of measuring a distance $z$ is $lambda e^(-lambda z)$; this is the probability that an unexpected object enters the FOV at distance $z$.

#align(center)[
  #image("/assets/unexpected_obstacles.png", width: 50%)
]

3. *Failures:* Point mass distribution concentrated at the maximum range ($z_"max"$).

#align(center)[
  #image("/assets/failure.png", width: 50%)
]

4. *Random noise:* Uniform distribution between $0$ and $z_"max"$. The probability of measuring a distance $z$ is $1/(z_"max")$; this is the probability that the sensor reports a random measurement.

#align(center)[
  #image("/assets/random_noise.png", width: 50%)
]

By mixing these four densities (using a weighted sum), we obtain the complete sensing model for a single beam:

$ p(z_i | s_t, m) = alpha_1 p_{"hit"} + alpha_2 p_{"unexp"} + alpha_3 p_{"fail"} + alpha_4 p_{"rand"} $

*How to set the intrinsic parameters $Theta = {alpha_1 ... alpha_4, sigma^2, lambda}$?*
We must gather data from the sensor and then use *MLE* (Maximum Likelihood Estimation) to fit the parameters to the real hardware.

==== Limitations of the Beam Model

The beam model has some significant limitations that make it difficult to use in practice:
- *Ray casting is an expensive procedure:* If the robot produces scans at high frequencies, computing the density based on the beam model might be too slow. (One workaround is to pre-compute distances from every location, but it takes memory).
- *Lack of smoothness:* The density $p(z_i|s_t, m)$ might be very *unsmooth* with respect to $s_t$. A very small change in the robot's pose $s_t$ might cause a huge change in what the correct reading should be (e.g., grazing the edge of a wall).
- The above factors result in increased difficulty in computing the state belief using the filter.

#informally[
  Let's try to build another way to explain the measurement which *does not* rely on generative dynamics. Instead of reasoning about what could happen along the beam, let's just consider where the beam landed: the *end point*.
]

== Likelihood Fields (Scan Model)

This approach is functionally equivalent, as it is still used to build a perception model for range finders, but it works in a fundamentally different and simpler way. 

Instead of simulating the entire path of the beam (ray casting), this model ignores the path and reasons exclusively about the *end point* of the measurement.

*Method:*
1. *Compute the end point coordinates:* First, we calculate the global coordinates $x_(z_i), y_(z_i)$ of the measurement's end point. This is done by projecting the measured distance $z_i$ into the map using the robot's current pose estimation and the sensor's relative heading.
2. *Discard invalid readings:* If $z_i = z_"MAX"$, discard it. Maximum range readings indicate a failure to hit anything, meaning their end point coordinates have no meaning on the map.
3. *Compute distance:* For valid readings, compute the Euclidean distance $d$ between this end point and the *closest* obstacle currently known on the map.
4. *Gaussian probability:* The probability of this measurement, $p_"hit"$, is modeled as a Gaussian with zero mean: $p_sigma(d)$, where $sigma$ is a sensor-specific noise parameter.
5. *Mixture of densities:* Similar to the beam model, this distribution is mixed to account for random noise and failures:
   $ p(z_i | s_t, m) = alpha_1 p_"hit" + alpha_2 p_"rnd" + alpha_3 p_"fail" $
   
*Limitation on unexpected obstacles:* Unexpected obstacles *cannot* be considered in this model because it completely ignores the path followed by the beam; it only considers the end point.

#note()[
  - *Why compute the closest obstacle?* We make the assumption that the nearest mapped obstacle is the one responsible for generating that specific end point. 
  - *Conceptually:* Around every physical object on the map, we imagine a "field" or a probabilistic region. If an end point falls within this region, the object explains that measurement. The closer the end point is to the obstacle, the higher the likelihood of the measurement. For every 2D location on the map, we have a $p_"hit"$ (the closer to an obstacle, the higher the probability).

  #align(center)[
    #image("/assets/image.png", width: 40%)
  ]
]