#import "../template.typ": *

= Robot Perception

Explain how the sensor arrives at a specific measurement, considering the sources of uncertainty that might affect it.

#note()[
  Sensors generate noise not only following a Gaussian distribution, but they also exhibit a more systematic error generation.
]

There are systematic ways of modeling noise beyond simply assuming a Gaussian distribution. The noise generated by a sensor is typically structured into various distinct components.

We must be very careful about how we model this noise.
The sensor model is fundamentally a conditional probability: 
$ p(z_t | s_t) $.

We will focus on one specific class of sensors: range finders.

#note()[
  A range finder is a laser device that shoots beams in different directions. When the laser hits an obstacle and reflects back, the sensor measures the time of flight (the time between emission and return) to determine the distance and orientation of the obstacle.
]

#warning()[
  Is the robot's position the only factor that influences its perception of the environment? NO
]

We need to introduce another critical element that influences the perception of a range finder: the *environment*, which we will formalize as the *map*.

In our model definition, we must include the map $m$ as part of our prior knowledge:

$ p(z_t | s_t, m) $

#note()[
  This assumption is not always true for modern robots, which often do not know the map beforehand and must build it incrementally (SLAM). However, for this theoretical context, we assume the map is known.
]

#note()[
  The map is typically a *discrete* representation of the environment.
]

If the robot does not know its position within this map, it faces the *localization problem*: "Where am I in the map?"

The map provides the necessary context to explain why the robot collected a specific set of measurements.

*Location-based map:* A location-based map is essentially a collection of elements, each corresponding to a specific location in the environment and reporting a set of features. This is often referred to as a _volumetric_ representation, distinguishing it from a feature-based map. A location-based map acts as a comprehensive grid where, for each possible small area (or cell) of the space, information regarding obstacle occupancy is provided (e.g., a binary "yes/no" or the continuous probability of an obstacle being present).

#note()[
  The location-based map is simpler to use but less flexible; conversely, a feature-based map is more flexible but more complex to use.
]

If the space is modeled as a discrete grid (similar to pixels covering a 2D plane area), we refer to these elements as cells. A cell $c$ can be represented by coordinates $x_c, y_c$, and its occupancy value is denoted as $o(c)$:

- $o(c) = 1$: Cell is occupied by an obstacle (black spot).
- $o(c) = 0$: Cell is free from obstacles (white spot).
- $0 < o(c) < 1$: The probability that the cell is occupied by an obstacle.

// Immagine mappa

#note()[
  Besides occupancy information, maps can also contain semantic information, characterizing the space by identifying features like "door", "kitchen", or the color of the cell, for example.
]

== Range Finders

They are a specific type of sensor that produces a scan $z$ composed of $K$ individual measurements:

$ z = {z_1, ..., z_K} $

Each measurement $z_i$ represents the distance from the robot's center to the *nearest* obstacle along the beam's specific heading.

// Immagine range finders

#warning()[
  Are the individual measurements dependent or independent?
]

If the robot's position in the map is unknown, the measurements are *dependent*: there is a high correlation between adjacent readings. 
However, given the map $m$ and the current pose $s_t$, all measurements are considered *conditionally independent*.
Since the map and the current pose fully describe the state, we can calculate the likelihood of an entire scan as the product of the likelihoods of individual measurements:

$ p(z | s_t, m) = product_(i = 1)^K p(z_i | s_t, m) $

This is the *sensor likelihood* or the *perception model* of the sensor, which essentially quantifies the reliability and accuracy of the sensor.

#informally()[
  The perception model tells us the limits of the sensor. For example, if the sensor can measure up to 10 meters, the perception model will tell us that the probability of measuring a distance greater than 10 meters is zero.
]

There are two primary models to explain how measurements are delivered by the sensor:

- Beam model: it explains the measurement of the sensor given the pose of the robot and the map of the environment.

- Likelihood fields (Scan model): it explains the measurement of the sensor given the pose of the robot and the map of the environment, but it also considers the uncertainty of the measurement.

=== Beam Model

#informally()[
  Let's analyze the physical journey of a laser beam starting from the robot and returning to it. We need to describe what could happen during the beam's travel.
]

If the current pose, the map, and the heading of the beam are known, we can compute the expected, ideal distance measurement, denoted as $z^*$.

#note()[
  This is similar to *forward kinematics* (given the current pose and the control action, I compute the next state).
]

We calculate $z^*$ via *ray casting/ray tracing*: we simulate the beam within the map and determine mathematically where it intersects an obstacle.

In an ideal, _noise-free_ scenario with zero uncertainty, the sensor would return exactly $z^*$. However, reality is imperfect. The actual measurement will likely be close to $z^*$, but affected by noise. This noise is caused by physical phenomena and "surprises" that occur during the beam's flight. 

#warning()[
  If we can comprehensively list all these potential interfering factors, we can build a probabilistic model to explain the measurements.
]

#informally()[
  What affects this ideal quantity $z^*$? What causes the gap between simulation and reality? 
]

- *Measurement noise (Timing precision):* Range finders measure time-of-flight. Since sensors lack 100% precision, the hardware introduces local Gaussian noise. The actual measurement will be distributed around the true distance $z^*$. Every sensor has an intrinsic noise.

- *Unexpected objects (Dynamic obstacles):* Entities that enter the field of view (FOV), such as people or dynamic objects not included in the static map $m$. These interrupt the beam *before* it hits the expected mapped obstacle, resulting in a shorter reading.

#note()[
  The greater the expected distance ($z^*$), the higher the probability that an unexpected object will intersect the beam's path.
]

- *Sensor Failures (Max range measurements):* If an obstacle absorbs the laser, reflects it away (specular reflection like a mirror), or if the obstacle is simply beyond the sensor's range, the sensor misses the returning beam. This typically results in the sensor returning its maximum possible distance value, acting as a failure state.

- *Random measurements:* Completely unexplained anomalies or random noise, sometimes caused by sensor crosstalk (interference from other active sensors) or phantom reflections.

// Explanation of probability density graphs

Each of these four phenomena is modeled mathematically by a specific probability density function:

1. *Measurement noise:* Gaussian distribution centered at the true distance $z^*$. This is the $z^*$ (random variable) plus a Gaussian noise with zero mean and variance $sigma^2$. If an obstacle is $5$ meters away, we have $0$ probability that the sensor reports $10$ meters, but we have a non-zero probability that the sensor reports $5.1$ meters; this is the noise of the sensor.

2. *Unexpected obstacles:* Exponential distribution (the probability of hitting an unmapped object decreases as distance increases) with parameter $lambda$. The probability of measuring a distance $z$ is $lambda e^(-lambda z)$; this is the probability that an unexpected object enters the FOV at distance $z$.

3. *Failures:* Point mass distribution concentrated at the maximum range ($z_"max"$).

4. *Random noise:* Uniform distribution between $0$ and $z_"max"$. The probability of measuring a distance $z$ is $1/(z_"max")$; this is the probability that the sensor reports a random measurement.

By mixing these four densities (using a weighted sum), we obtain the complete sensing model for a single beam:

$ p(z_i | s_t, m) $

There is, however, an alternative and often computationally simpler way to build a perception model.

== Likelihood Fields (Scan Model)

This approach is functionally equivalent, as it is still used to build a perception model for range finders, but it works in a fundamentally different and simpler way. 

Instead of simulating the entire path of the beam (ray casting), this model reasons exclusively about the *end point* of the measurement.

- *Compute the coordinates:* First, we calculate the global coordinates $(x, y)$ of the measurement's end point. This is done by projecting the measured distance $z_i$ into the map using the robot's current pose estimation and the sensor's relative heading.
- *Discard invalid readings:* If $z_i = z_"max"$, the measurement is discarded. Maximum range readings indicate a failure to hit anything, meaning their end point coordinates have no physical meaning on the map.
- *Compute distance:* For valid readings, we compute the Euclidean distance $d$ between this end point and the *closest* obstacle currently known on the map.
- *Gaussian probability:* The probability of this measurement, $p_"hit"$, is modeled as a zero-mean Gaussian distribution over the distance $d$: $p_sigma(d)$, where $sigma$ is a sensor-specific noise parameter.
- *Mixture of densities:* Similar to the beam model, this distribution is mixed with a uniform distribution to account for random noise.
- *Limitation on unexpected obstacles:* Unexpected or dynamic obstacles *cannot* be considered in this model. Because it completely ignores the physical path followed by the beam, it cannot detect if an object interrupted the laser midway; it only looks at where the beam stopped.

#note()[
  - *Why compute the closest obstacle?* We make the assumption that the nearest mapped obstacle is the one responsible for generating that specific end point. 
  - *Conceptually:* Around every physical object on the map, we imagine a "field" or a probabilistic region. If an end point falls within this region, the object explains that measurement. The closer the end point is to the obstacle, the higher the likelihood of the measurement.
]